# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 07:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2016, 2, 4, 7, 23, 37, 629113, tzinfo=utc))),
                ('videourl', models.URLField(default='')),
                ('pdfdocument', models.FileField(blank=True, null=True, upload_to='event/')),
            ],
        ),
        migrations.CreateModel(
            name='EventCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('note', models.CharField(default='', max_length=400)),
                ('trackdate', models.DateField(auto_now=True)),
                ('tracktime', models.TimeField(auto_now=True)),
                ('checkintime', models.DateTimeField(default=datetime.datetime(2016, 2, 4, 7, 23, 37, 630759, tzinfo=utc))),
                ('checkouttime', models.DateTimeField(blank=True, null=True)),
                ('completeflag', models.BooleanField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('location', models.CharField(default='', max_length=400)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admininterface.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admininterface.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admininterface.Event'),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
    ]
