# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('cif', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('score', models.CharField(blank=True, max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='event/user/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2016, 2, 8, 9, 52, 12, 107377, tzinfo=utc))),
                ('videourl', models.URLField(default='')),
                ('pdfdocument', models.FileField(blank=True, null=True, upload_to='event/')),
                ('user', models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('note', models.CharField(default='', max_length=400)),
                ('brief_opened', models.BooleanField(default=False)),
                ('trackdate', models.DateField(auto_now=True)),
                ('tracktime', models.TimeField(auto_now=True)),
                ('checkintime', models.DateTimeField(default=datetime.datetime(2016, 2, 8, 9, 52, 12, 108763, tzinfo=utc))),
                ('checkouttime', models.DateTimeField(blank=True, null=True)),
                ('completeflag', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('location', models.CharField(default='', max_length=400)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admininterface.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCheckImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event/photo/')),
                ('eventcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admininterface.EventCheck')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400)),
                ('brand', models.CharField(default='', max_length=400)),
                ('format', models.CharField(default='', max_length=400)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admininterface.Event')),
            ],
        ),
    ]
