# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 8, 14, 40, 929177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 8, 14, 40, 930659, tzinfo=utc)),
        ),
    ]
