# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0002_auto_20160204_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 12, 50, 30, 779012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 12, 50, 30, 781376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='type',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
