# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0003_auto_20160210_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 8, 41, 39, 761219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 8, 41, 39, 762611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('MALE', 'male'), ('FEMALE', 'female')], default='UNKNOWN', max_length=30),
        ),
    ]
