# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0003_auto_20160204_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='event/pictures/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 14, 12, 24, 195860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 14, 12, 24, 201989, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventcheckimage',
            name='eventcheck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admininterface.EventCheck'),
        ),
    ]
