# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0004_auto_20160204_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcheckimage',
            name='picture',
        ),
        migrations.AddField(
            model_name='eventcheckimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event/photo/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 14, 43, 37, 854331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 14, 43, 37, 856575, tzinfo=utc)),
        ),
    ]
