# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0004_auto_20160210_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 12, 30, 14, 85671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 12, 30, 14, 87066, tzinfo=utc)),
        ),
    ]
