# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0005_auto_20160210_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brief',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventuser_objective_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 15, 25, 23, 100848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='checkintime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 15, 25, 23, 102837, tzinfo=utc)),
        ),
    ]
